-- ============================================
-- Plantilla SpeedLaunch — Método CLEE
-- Ejecutar en el SQL Editor de Supabase
-- ============================================

INSERT INTO portal.project_templates (name, description, tasks, milestones)
VALUES (
  'SpeedLaunch - Método CLEE',
  'Plantilla completa del Método CLEE con 5 fases: Análisis y Diagnóstico, Creación, Lanzamiento + Validación, Eficientizar con IA, y Sistemas + Escalado.',
  '[
    {"title":"Compartir Métricas","description":"El cliente debe compartir todas las métricas actuales de su negocio para que el equipo pueda analizarlas.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Métricas","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Analizar Métricas","description":"Análisis detallado de las métricas compartidas por el cliente.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Métricas","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Generar Informe de Métricas","description":"Crear informe con hallazgos y recomendaciones basadas en las métricas.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Métricas","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Revisión de Métricas","description":"Llamada conjunta para revisar el informe de métricas.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Métricas","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Compartir Referentes","description":"El cliente comparte sus referentes de competencia.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Inv. Competencia","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Análisis de Referentes","description":"Investigación y análisis de los referentes del mercado.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Inv. Competencia","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Generar Informe de Competencia","description":"Crear informe con el análisis de la competencia.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Inv. Competencia","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Llamada Análisis Competencia","description":"Llamada conjunta para revisar el análisis de competencia.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Inv. Competencia","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Llamada Historia del Héroe","description":"Sesión para definir la historia del héroe de la marca.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Historia del Héroe","assigned_to":"JC+MP","priority":"high","status":"backlog"},
    {"title":"Elaborar Encuesta","description":"Crear la encuesta para la audiencia.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Encuesta Audiencia","assigned_to":"JC+MP","priority":"high","status":"backlog"},
    {"title":"Distribuir Encuesta","description":"El cliente distribuye la encuesta entre su audiencia.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Encuesta Audiencia","assigned_to":"MP","priority":"high","status":"backlog"},
    {"title":"Análisis de Encuesta","description":"Analizar los resultados de la encuesta.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Encuesta Audiencia","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Revisión de Análisis de Encuesta","description":"Revisar conjuntamente los hallazgos de la encuesta.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Encuesta Audiencia","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Creación de Clusters","description":"Crear grupos/clusters de audiencia.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Avatares y BP","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Análisis Avatares 12 bloques","description":"Análisis detallado de avatares con metodología de 12 bloques.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Avatares y BP","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Revisión de Avatares","description":"Revisión conjunta de los avatares creados.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Avatares y BP","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Análisis Actual + Visión","description":"El cliente analiza su oferta actual y define su visión.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Optimización de Oferta","assigned_to":"MP","priority":"high","status":"backlog"},
    {"title":"Análisis Actual + Propuesta Estratégica","description":"JoinsClee analiza la oferta y prepara propuesta estratégica.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Optimización de Oferta","assigned_to":"JC","priority":"high","status":"backlog"},
    {"title":"Revisión Conjunta + Definición de Oferta","description":"Definir la oferta final entre ambas partes.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Optimización de Oferta","assigned_to":"JC+MP","priority":"high","status":"backlog"},
    {"title":"Evaluación Actual + Propuesta Estratégica de Producto","description":"Evaluar el producto actual y proponer mejoras.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Mejora de Producto","assigned_to":"JC+MP","priority":"high","status":"backlog"},
    {"title":"Revisión Final de Producto","description":"Revisión final de las mejoras propuestas al producto.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Mejora de Producto","assigned_to":"JC+MP","priority":"high","status":"backlog"},
    {"title":"Branding","description":"Revisión y mejora de la identidad de marca.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Coherencia de Marca","assigned_to":"MP","priority":"urgent","status":"backlog"},
    {"title":"Fotografía","description":"Sesión fotográfica profesional para la marca.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Coherencia de Marca","assigned_to":"MP","priority":"urgent","status":"backlog"},
    {"title":"Contenidos de Marca","description":"Crear contenidos coherentes con la marca.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Coherencia de Marca","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"PUV Marca","description":"Crear la Propuesta Única de Valor de la marca.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Creación de PUVs","assigned_to":"JC+MP","priority":"high","status":"backlog"},
    {"title":"PUV Producto","description":"Crear la Propuesta Única de Valor del producto.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Creación de PUVs","assigned_to":"JC+MP","priority":"high","status":"backlog"},
    {"title":"PUV Lanzamiento","description":"Crear la Propuesta Única de Valor del lanzamiento.","phase":"Fase 0 - Análisis y Diagnóstico","group":"Creación de PUVs","assigned_to":"JC+MP","priority":"high","status":"backlog"},

    {"title":"Construcción del Espacio","description":"Construir el espacio digital de la comunidad.","phase":"Fase 1 - Creación","group":"Casa Digital - Comunidad","assigned_to":"JC+MP","priority":"urgent","status":"backlog"},
    {"title":"Definir Módulos y Escalera de Valor","description":"Definir la estructura de módulos y la escalera de valor.","phase":"Fase 1 - Creación","group":"Casa Digital - Comunidad","assigned_to":"JC+MP","priority":"urgent","status":"backlog"},
    {"title":"Definir Gamificación","description":"Definir gamificación si aplica al proyecto.","phase":"Fase 1 - Creación","group":"Casa Digital - Comunidad","assigned_to":"JC+MP","priority":"urgent","status":"backlog"},
    {"title":"Cargar o Crear Productos/Cursos","description":"Subir o crear los productos/cursos al espacio digital.","phase":"Fase 1 - Creación","group":"Casa Digital - Comunidad","assigned_to":"MP","priority":"high","status":"backlog"},
    {"title":"Crear, Grabar y Montar Empieza Aquí","description":"Producir el contenido de bienvenida.","phase":"Fase 1 - Creación","group":"Casa Digital - Comunidad","assigned_to":"MP","priority":"high","status":"backlog"},
    {"title":"Definir, Grabar y Montar Reglas","description":"Producir el contenido de reglas de la comunidad.","phase":"Fase 1 - Creación","group":"Casa Digital - Comunidad","assigned_to":"MP","priority":"high","status":"backlog"},
    {"title":"Definir Frecuencia de Llamadas y Agendar","description":"Definir calendario de llamadas con la comunidad.","phase":"Fase 1 - Creación","group":"Casa Digital - Comunidad","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Crear Business Manager Meta","description":"Crear la cuenta de Business Manager en Meta.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Configurar Business Manager Meta","description":"Configurar correctamente el Business Manager.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Cuenta GHL + Configuración","description":"Crear y configurar la cuenta de GoHighLevel.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Construir Embudos","description":"Crear los embudos de venta en la plataforma.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Crear Página de Registro","description":"Diseñar y montar la página de registro.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Página de Registro - VSL","description":"Producir el Video Sales Letter para registro.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Página de Registro - Copys","description":"Crear los textos persuasivos de la página de registro.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Página de Registro - Revisión Final","description":"Revisión final de la página de registro completa.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Crear Página de Gracias","description":"Diseñar y montar la página de agradecimiento.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Página de Gracias - Copys","description":"Crear los textos de la página de gracias.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Página de Gracias - VSL","description":"Producir video para la página de gracias.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Página de Gracias - Conectar WhatsApp","description":"Integrar WhatsApp con la página de gracias.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Cuenta Funnelchat","description":"Crear cuenta en Funnelchat.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Configuración Funnelchat","description":"Configurar Funnelchat para automatización.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Crear Comunidad WhatsApp","description":"Crear y configurar la comunidad de WhatsApp.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Automatización de Correos","description":"Configurar secuencias automáticas de correo.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Prueba de Embudos (Customer Journey)","description":"Probar todo el recorrido del cliente por los embudos.","phase":"Fase 1 - Creación","group":"Sistemas de Venta","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Comunicación Orgánica","description":"Definir la estrategia de comunicación orgánica.","phase":"Fase 1 - Creación","group":"Estrategia de Contenido","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Definir Roles de Redes Sociales","description":"Asignar roles y responsabilidades para cada red social.","phase":"Fase 1 - Creación","group":"Estrategia de Contenido","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Ads - Estrategia","description":"Definir la estrategia publicitaria.","phase":"Fase 1 - Creación","group":"Estrategia de Contenido","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Revisión de OMV","description":"Revisar la Oferta Mínima Viable del producto.","phase":"Fase 1 - Creación","group":"Producto","assigned_to":"JC+MP","priority":"medium","status":"backlog"},

    {"title":"Contenido Orgánico - Guionización","description":"Escribir guiones para contenido orgánico de captación.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Contenido Orgánico - Grabación","description":"Grabar el contenido orgánico.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Contenido Orgánico - Edición","description":"Editar el contenido orgánico grabado.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Contenido Orgánico - Ejecución","description":"Publicar y ejecutar el contenido orgánico.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Ads - Guionización","description":"Escribir guiones para anuncios pagados.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Ads - Grabación","description":"Grabar los anuncios.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Ads - Edición","description":"Editar los anuncios grabados.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Ads - Ejecución de Campañas","description":"Lanzar y ejecutar las campañas publicitarias.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Ads - Seguimiento y Optimización","description":"Seguimiento y optimización de las campañas activas.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Ads Retargeting WhatsApp","description":"Configurar campañas de retargeting vía WhatsApp.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Mails - Guionización","description":"Escribir los correos de la secuencia de captación.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Mails - Ejecución","description":"Ejecutar la secuencia de correos.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Invitación","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Guionizar WhatsApp","description":"Crear guiones para comunicación por WhatsApp.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Conciencia","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Guionizar Mail","description":"Crear guiones para correos de conciencia.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Conciencia","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Regalo Día 1","description":"Preparar y entregar el regalo del día 1.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Conciencia","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Estrategia YouTube Píldoras","description":"Definir estrategia de píldoras de contenido en YouTube.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Conciencia","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Grabación YouTube Píldoras","description":"Grabar las píldoras de contenido.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Conciencia","assigned_to":"MP","priority":"medium","status":"backlog"},
    {"title":"Edición YouTube Píldoras","description":"Editar las píldoras de contenido.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Conciencia","assigned_to":"JC","priority":"medium","status":"backlog"},
    {"title":"Encuesta de Conciencia","description":"Crear y distribuir encuesta de la fase de conciencia.","phase":"Fase 2 - Lanzamiento + Validación","group":"Captación - Conciencia","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Entrenamiento","description":"Fase de entrenamiento del lanzamiento.","phase":"Fase 2 - Lanzamiento + Validación","group":"Entrenamiento","assigned_to":"JC+MP","priority":"medium","status":"backlog"},
    {"title":"Venta","description":"Fase de venta del lanzamiento.","phase":"Fase 2 - Lanzamiento + Validación","group":"Venta","assigned_to":"JC+MP","priority":"medium","status":"backlog"},

    {"title":"Implementar IA en Procesos","description":"Identificar e implementar herramientas de IA para eficientizar procesos.","phase":"Fase 3 - Eficientizar con IA","group":"IA","assigned_to":"JC+MP","priority":"medium","status":"backlog"},

    {"title":"Crear SOPs + Plan de Escalado","description":"Documentar procesos operativos estándar y crear plan de escalado.","phase":"Fase 4 - Sistemas + Escalado","group":"Sistemas","assigned_to":"JC+MP","priority":"medium","status":"backlog"}
  ]'::jsonb,
  '[
    {"name":"Fase 0 - Análisis y Diagnóstico","status":"pending"},
    {"name":"Fase 1 - Creación","status":"pending"},
    {"name":"Fase 2 - Lanzamiento + Validación","status":"pending"},
    {"name":"Fase 3 - Eficientizar con IA","status":"pending"},
    {"name":"Fase 4 - Sistemas + Escalado","status":"pending"}
  ]'::jsonb
);
